const admin = {
  login: 'Login', username: 'Username', password: 'Password', loginBtn: 'Sign in', loginOk: 'Logged in',
  adminConsole: 'Admin Console', secureLogin: 'Secure Login', loginTitle: 'Manage your content universe', loginSubtitle: 'Maintain posts, projects, resources, and profile data with a clean publishing workflow.', loginHint: 'Use your admin account to continue', contentGuard: 'Content guard', dataSync: 'Data sync', visualManage: 'Visual ops',
  dashboard: 'Dashboard', articles: 'Articles', projects: 'Projects', resources: 'Resources', messages: 'Messages', siteConfig: 'Site Config', profile: 'Profile',
  backHome: 'Back to site', logout: 'Logout',
  totalViews: 'Total Views', articleCount: 'Articles', publishedCount: 'Published', projectCount: 'Projects', messageCount: 'Messages',
  overview: 'Operations', overviewDesc: 'Current status of publishing, resources, and comments.', publishedWithDraft: 'Published {{published}}, draft {{draft}}', resourceCount: 'Resources', resourceMaintain: 'Maintain tools, docs, and links', totalMessages: 'Total comments', activityTrend: 'Activity Trend', contentDistribution: 'Content Distribution', total: 'Total', contentItems: 'Content', operationReminder: 'Reminders', pendingMessages: '{{count}} comments pending', messageManage: 'Comment management', messageManageDesc: 'Review, verify, and clean visitor comments.', draftArticles: '{{count}} draft articles', contentManage: 'Content management', featuredProjects: '{{count}} featured projects', projectManage: 'Project management', projectManageDesc: 'Maintain project works, display order, tags, and links.', resourceManage: 'Resource management', resourceManageDesc: 'Maintain tools, references, categories, and links.', recentArticles: 'Recent Articles', commentActivity: 'Comment Activity', noMessages: 'No comments', noMessagesDesc: 'Everything is clean for now.',
  newArticle: 'New Article', newProject: 'New Project', newResource: 'New Resource', viewArticle: 'View Article', viewProject: 'View Project', viewResource: 'View Resource', editProject: 'Edit Project', editResource: 'Edit Resource', edit: 'Edit', delete: 'Delete', save: 'Save', title: 'Title', status: 'Status', published: 'Published', draft: 'Draft', views: 'Views', updatedAt: 'Updated', actions: 'Actions',
  articleManage: 'Article Management', articleManageDesc: 'Maintain bilingual posts, publishing status, tags, and assets.', refresh: 'Refresh', allArticles: 'All Articles', featured: 'Featured', keyword: 'Keyword', keywordPlaceholder: 'Title / Slug', allStatus: 'All Status', search: 'Search', reset: 'Reset', article: 'Article',
  editArticle: 'Edit Article', editorDesc: 'Write, preview, manage cover assets, and publish without jumping around.', unsaved: 'Unsaved', savedState: 'Saved', leaveConfirm: 'You have unsaved changes. Leave this page?',
  publishSettings: 'Publish Settings', coverPreview: 'Cover Preview', noCover: 'No cover yet', uploadCover: 'Upload Cover', coverUrl: 'Cover image URL', writingArea: 'Writing', preview: 'Preview', contentPlaceholder: 'Start writing Markdown and the preview will appear here.', titlePlaceholder: 'Enter article title', summaryPlaceholder: 'Summarize the article in one or two sentences', tagsPlaceholder: 'Type a tag and press Enter', tagHelper: 'You can type new tags or pick existing ones. Commas split tags automatically.',
  confirmDelete: 'Delete this item?', deleted: 'Deleted', saved: 'Saved',
  zhTab: 'Chinese', enTab: 'English', articleTitle: 'Title', summary: 'Summary', content: 'Content (Markdown)', cover: 'Cover', tags: 'Tags', slug: 'Slug',
  heroConfig: 'Hero Section', siteConfigDesc: 'Maintain homepage hero copy, feature entries, weather city, and announcement.', basicConfig: 'Basic Config', homePreview: 'Homepage Preview', homePreviewDesc: 'These settings affect the public homepage hero, feature cards, and announcement area.', configTip: 'Config Tip', configTipDesc: 'Feature entries are fixed to 6 slots. Fill in bilingual titles and descriptions for each slot.', greeting: 'Greeting', titleZh: 'Title (ZH)', titleEn: 'Title (EN)', descZh: 'Description (ZH)', descEn: 'Description (EN)',
  featuresConfig: 'Feature Cards (6 entries)', weatherCity: 'Weather city (EN)', announcement: 'Announcement',
  profileDesc: 'Manage your profile and public display information.', basicInfo: 'Basic Info', accountOverview: 'Account Overview', adminRole: 'Admin', email: 'Email', accountRole: 'Role', accountStatus: 'Status', normal: 'Normal',
  name: 'Name', avatar: 'Avatar', bioZh: 'Bio (ZH)', bioEn: 'Bio (EN)', location: 'Location', socials: 'Social links', messageDetail: 'Message Detail',
  featuredProject: 'Featured', sort: 'Sort', link: 'Link', category: 'Category', nickname: 'Nickname',
};

export default admin;
